# Generated by Django 3.0.8 on 2020-07-18 18:19

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('contacts', models.TextField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('tags', sortedm2m.fields.SortedManyToManyField(help_text=None, to='goods_service.AdvertTag')),
            ],
        ),
    ]
