# Generated by Django 3.0.8 on 2020-07-21 11:01

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    replaces = [('goods_service', '0001_initial'), ('goods_service', '0002_auto_20200718_2312'), ('goods_service', '0003_auto_20200718_2338'), ('goods_service', '0004_auto_20200719_0900'), ('goods_service', '0005_advertimage'), ('goods_service', '0006_auto_20200719_1208'), ('goods_service', '0007_auto_20200719_1431'), ('goods_service', '0008_auto_20200719_1450'), ('goods_service', '0009_auto_20200719_1544'), ('goods_service', '0010_auto_20200719_1544'), ('goods_service', '0011_auto_20200719_1547'), ('goods_service', '0012_auto_20200719_1552'), ('goods_service', '0013_auto_20200719_1636'), ('goods_service', '0014_auto_20200719_1802'), ('goods_service', '0015_auto_20200721_1055')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('contacts', models.TextField(max_length=300)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('tags', sortedm2m.fields.SortedManyToManyField(help_text=None, to='goods_service.AdvertTag')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='img')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='goods_service.Advert')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
