# Generated by Django 3.0.8 on 2020-07-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
