# Generated by Django 3.0.8 on 2020-07-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_service', '0003_auto_20200718_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverttag',
            options={'ordering': ['name']},
        ),
    ]
