# Generated by Django 3.0.8 on 2020-07-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_service', '0004_auto_20200719_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_service.Advert')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
