"""subject

Revision ID: 11014ce241a6
Revises: 398d512c4727
Create Date: 2020-08-11 23:31:56.790883

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "11014ce241a6"
down_revision = "398d512c4727"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "templates",
        sa.Column(
            "subject", sa.String(length=200), nullable=False, server_default="None"
        ),
    )
    op.alter_column("templates", "subject", server_default=None)
    op.create_unique_constraint(None, "templates", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "templates", type_="unique")
    op.drop_column("templates", "subject")
    # ### end Alembic commands ###
